# Generated by Django 4.0.6 on 2022-08-11 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_website', models.BooleanField(default=False, verbose_name='Website')),
                ('is_application', models.BooleanField(default=False, verbose_name='Application')),
                ('app_name', models.CharField(max_length=200)),
                ('companyURL', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('policy_date', models.DateField()),
                ('is_email_collected', models.BooleanField(default=False, verbose_name='Email Address')),
                ('is_first_name_collected', models.BooleanField(default=False, verbose_name='First name and last name')),
                ('is_phonenumber_collected', models.BooleanField(default=False, verbose_name='Phone number')),
                ('is_address_collected', models.BooleanField(default=False, verbose_name='Address, state, city, zip/postal code')),
                ('is_social_collected', models.BooleanField(default=False, verbose_name='Social medial profile information')),
                ('is_others_collected', models.BooleanField(default=False, verbose_name='Others')),
                ('your_other_collected', models.CharField(blank=True, default='', max_length=200)),
                ('analytic', models.CharField(max_length=100)),
                ('email_to_user', models.CharField(max_length=100)),
                ('display_ads', models.CharField(max_length=100)),
                ('pay_for_service', models.CharField(max_length=100)),
                ('collect_information_from_kids', models.CharField(max_length=100)),
                ('is_email_contacted', models.BooleanField(default=False, verbose_name='Email Address')),
                ('is_website_contacted', models.BooleanField(default=False, verbose_name='A page on our website')),
                ('is_phone_contacted', models.BooleanField(default=False, verbose_name=' Phone num')),
                ('is_post_mail_contected', models.BooleanField(default=False, verbose_name='Sending post mail')),
                ('is_i_agree', models.BooleanField(default=False, verbose_name='I agree to the Policify Terms and Conditions and Privacy Policy')),
                ('is_notify_me', models.BooleanField(default=False, verbose_name='Notify me of Policify policy updates.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
