# Generated by Django 4.0.6 on 2022-08-12 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policifyapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_website', models.BooleanField(default=False, verbose_name='Website')),
                ('is_application', models.BooleanField(default=False, verbose_name='Application')),
                ('app_name', models.CharField(max_length=200)),
                ('companyURL', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('policy_date', models.DateField()),
                ('create_account', models.CharField(max_length=100)),
                ('upload_content', models.CharField(max_length=100)),
                ('in_app_purchases', models.CharField(max_length=100)),
                ('display_ads', models.CharField(max_length=100)),
                ('buy_goods', models.CharField(max_length=100)),
                ('subscription_plans', models.CharField(max_length=100)),
                ('exclusive', models.CharField(max_length=100)),
                ('is_email_contacted', models.BooleanField(default=False, verbose_name='Email Address')),
                ('is_website_contacted', models.BooleanField(default=False, verbose_name='A page on our website')),
                ('is_phone_contacted', models.BooleanField(default=False, verbose_name=' Phone num')),
                ('is_post_mail_contected', models.BooleanField(default=False, verbose_name='Sending post mail')),
                ('is_i_agree', models.BooleanField(default=False, verbose_name='I agree to the Policify Terms and Conditions and Privacy Policy')),
                ('is_notify_me', models.BooleanField(default=False, verbose_name='Notify me of Policify policy updates.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
